import { Product } from './types';

// Static seed data used for UI development before Firebase is connected
export const PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    sku: 'RKF260601',
    name: 'Avakaya – Mango Pickle',
    nameTeluguScript: 'అవకాయ',
    slug: 'avakaya-mango-pickle',
    category: 'pickles',
    dietType: 'veg',
    description:
      'Crisp, raw green mango chunks marinated in a fiery blend of coarse mustard powder, sun-dried red chili, and cold-pressed sesame oil. The quintessential Telugu pickle, perfected over generations.',
    ingredients: ['Raw green mango', 'Mustard powder', 'Red chili powder', 'Rock salt', 'Cold-pressed sesame oil', 'Fenugreek'],
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80'],
    actualPrice: 299,
    sellingPrice: 249,
    rating: 4.8,
    reviewCount: 312,
    inStock: true,
    availableLocations: ['Hyderabad', 'Vijayawada', 'Visakhapatnam', 'Chennai', 'Bangalore'],
    heatLevel: 8,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-002',
    sku: 'RKF260602',
    name: 'Nimma – Lemon Pickle',
    nameTeluguScript: 'నిమ్మ',
    slug: 'nimma-lemon-pickle',
    category: 'pickles',
    dietType: 'veg',
    description:
      'Thin-skinned yellow lemons cured in rock salt, fenugreek, and bold chili powder. Robust sour, salty and tangy — a classic Telugu pantry staple.',
    ingredients: ['Yellow lemons', 'Rock salt', 'Fenugreek', 'Red chili powder', 'Sesame oil'],
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&q=80'],
    actualPrice: 249,
    sellingPrice: 199,
    rating: 4.6,
    reviewCount: 198,
    inStock: true,
    availableLocations: ['Hyderabad', 'Vijayawada', 'Visakhapatnam'],
    heatLevel: 6,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-003',
    sku: 'RKF260603',
    name: 'Magaya – Dried Mango Pickle',
    nameTeluguScript: 'మగాయ',
    slug: 'magaya-dried-mango-pickle',
    category: 'pickles',
    dietType: 'veg',
    description:
      'Sun-dried, peeled mango strips seasoned with mustard and fenugreek. Rich, concentrated sourness with every bite — a unique dried-mango experience.',
    ingredients: ['Sun-dried mango', 'Mustard seeds', 'Fenugreek', 'Chili powder', 'Salt', 'Sesame oil'],
    imageUrl: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1625398407796-82650a8c135f?w=600&q=80'],
    actualPrice: 279,
    sellingPrice: 229,
    rating: 4.5,
    reviewCount: 145,
    inStock: true,
    availableLocations: ['Hyderabad', 'Vijayawada'],
    heatLevel: 5,
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-004',
    sku: 'RKF260604',
    name: 'Karivepaku – Curry Leaf Pickle',
    nameTeluguScript: 'కరివేపాకు',
    slug: 'karivepaku-curry-leaf-pickle',
    category: 'pickles',
    dietType: 'veg',
    description:
      `Intensely savory, herbaceous paste of fresh curry leaves, tamarind pulp, garlic cloves, and toasted spices. Unlike anything you've tasted before.`,
    ingredients: ['Fresh curry leaves', 'Tamarind pulp', 'Garlic', 'Mustard seeds', 'Dried chili', 'Sesame oil'],
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80'],
    actualPrice: 249,
    sellingPrice: 199,
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    availableLocations: ['Hyderabad', 'Vijayawada', 'Chennai'],
    heatLevel: 7,
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-005',
    sku: 'RKF260605',
    name: 'Gongura Pickle',
    nameTeluguScript: 'కూవేవాకు',
    slug: 'gongura-sorrel-pickle',
    category: 'pickles',
    dietType: 'veg',
    description:
      'Highly acidic, tangy sorrel leaves cooked with garlic and dried red chilies. A beloved rural Telugu classic that defines Andhra cuisine.',
    ingredients: ['Sorrel (gongura) leaves', 'Garlic', 'Dried red chilies', 'Mustard seeds', 'Oil', 'Salt'],
    imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600&q=80'],
    actualPrice: 269,
    sellingPrice: 219,
    rating: 4.9,
    reviewCount: 421,
    inStock: true,
    availableLocations: ['Hyderabad', 'Vijayawada', 'Visakhapatnam', 'Chennai', 'Bangalore', 'Mumbai'],
    heatLevel: 9,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-006',
    sku: 'RKF260606',
    name: 'Atreyapuram Pootharekulu',
    nameTeluguScript: 'ఆత్రేయపురం పూతరేకులు',
    slug: 'atreyapuram-pootharekulu',
    category: 'sweets',
    description:
      'Wafer-thin, translucent sheets of rice starch folded with pure ghee, sugar, cardamom, and chopped dry fruits. The crown jewel of Andhra sweets.',
    ingredients: ['Rice starch', 'Pure ghee', 'Sugar', 'Cardamom', 'Cashews', 'Almonds', 'Dry fruits'],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'],
    actualPrice: 599,
    sellingPrice: 499,
    rating: 4.9,
    reviewCount: 267,
    inStock: true,
    availableLocations: ['Hyderabad', 'Vijayawada', 'Visakhapatnam', 'Chennai', 'Bangalore', 'Mumbai', 'Delhi'],
    heatLevel: 3, // sweetness level
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-007',
    sku: 'RKF260607',
    name: 'Nethi Ariselu',
    nameTeluguScript: 'నేతి అరిసెలు',
    slug: 'nethi-ariselu',
    category: 'sweets',
    description:
      'Deep-fried golden discs of wet rice flour and jaggery, saturated with pure desi ghee and topped with toasted sesame seeds. A traditional Sankranti delicacy.',
    ingredients: ['Wet rice flour', 'Jaggery', 'Pure desi ghee', 'Sesame seeds', 'Cardamom'],
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80'],
    actualPrice: 449,
    sellingPrice: 379,
    rating: 4.7,
    reviewCount: 134,
    inStock: true,
    availableLocations: ['Hyderabad', 'Vijayawada', 'Visakhapatnam'],
    heatLevel: 6, // sweetness
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-008',
    sku: 'RKF260608',
    name: 'Bandar Laddu',
    nameTeluguScript: 'బందరు లడ్డు',
    slug: 'bandar-laddu',
    category: 'sweets',
    description:
      'Velvety, smooth gram flour spheres slow-roasted in ghee and cardamom, containing a whole chewy raisin inside. The legendary sweet of Machilipatnam.',
    ingredients: ['Gram flour (besan)', 'Pure ghee', 'Sugar syrup', 'Cardamom', 'Raisins', 'Cashews'],
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&q=80'],
    actualPrice: 499,
    sellingPrice: 419,
    rating: 4.8,
    reviewCount: 389,
    inStock: true,
    availableLocations: ['Hyderabad', 'Vijayawada', 'Visakhapatnam', 'Chennai', 'Bangalore', 'Mumbai', 'Delhi'],
    heatLevel: 8, // sweetness
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const FEATURED_PRODUCTS = PRODUCTS.filter((p) => p.featured);
export const PICKLE_PRODUCTS = PRODUCTS.filter((p) => p.category === 'pickles');
export const SWEET_PRODUCTS = PRODUCTS.filter((p) => p.category === 'sweets');
